services:
  postgres12:
    container_name: postgres12
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vet_database
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vet_network

  postgres12_test:
    container_name: postgres12_test
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vet_database_test
    ports:
      - "5430:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    networks:
      - vet_network

  api:
    container_name: clinical_vet_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres12
      - postgres12_test
    networks:
      - vet_network

networks:
  vet_network:

volumes:
  pgdata:
  pgdata_test:
